name: Deploy Static Website to Azure Storage

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload static site to Azure Storage
      uses: azure/cli@v2
      with:
        inlineScript: |
          az storage blob sync \
            --account-name finsrudfrukt \
            --source . \
            --container '$web' \
            --auth-mode login \
            --delete-destination true \
            --exclude-path ".github/*" "functions/*" \
            --exclude-pattern "*.md" "docker-compose.yml"
