name: Deploy Static Site to Azure Storage

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload static site to $web container
      uses: azure/cli@v2
      with:
        inlineScript: |
          az storage blob upload-batch \
            --destination '$web' \
            --account-name finsrudfrukt \
            --pattern '*.html' \
            --overwrite true \
            --auth-mode login \
            --source .

          az storage blob upload-batch \
            --destination '$web' \
            --account-name finsrudfrukt \
            --pattern '*.css' \
            --overwrite true \
            --auth-mode login \
            --source .

          az storage blob upload-batch \
            --destination '$web' \
            --account-name finsrudfrukt \
            --pattern '*.js' \
            --overwrite true \
            --auth-mode login \
            --source .

          az storage blob upload-batch \
            --destination '$web/images' \
            --account-name finsrudfrukt \
            --auth-mode login \
            --overwrite true \
            --source ./images

    - name: Logout of Azure
      if: always()
      run: az logout
